framework:
    messenger:
        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\Command\AddProduct':  amqp
            'App\Message\Command\DeleteProduct':  amqp
            'App\Message\Command\EditProduct':  amqp
        buses:
            messenger.bus.default:
                default_middleware: true
            messenger.bus.with_validation:
                default_middleware: true
                middleware:
                    - {id: 'messenger.middleware.validation'}
        default_bus: 'messenger.bus.default'