App\Entity\Product:
    properties:
        sku:
            - NotBlank: ~
            - Length:
                min: 2
                max: 254
            - App\Validator\Constraints\UniqueProductSku: ~
        price:
            - NotBlank: ~
            - Type:
                type: numeric
            - LessThanOrEqual: 9999999999.9999
            - GreaterThan: 0
        name:
            - NotBlank: ~
            - Length:
                min: 5
                max: 254
        description:
            - Length:
                max: 4000
