App\Entity\User:
  properties:
    email:
    - NotBlank: ~
    - Length:
        min: 5
        max: 254
    - Email: ~
    password:
    - NotBlank: ~
    - Length:
        min: 5
        max: 254
    - Regex:
        pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/'
        message: 'Password must contain both upper and lower case characters, have digits'
