App\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: bigint
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
